function r=integrand_nonlinear_function_2(x,y,solution_1_large_ele,solution_1_small_ele,solution_2_large_ele,solution_2_small_ele,basis_type,normal)

r=-0.25*((fe_solution(x,y,solution_1_large_ele,0,0,basis_type)-fe_solution(x,y,solution_1_small_ele,0,0,basis_type))*normal(1)...
        +(fe_solution(x,y,solution_2_large_ele,0,0,basis_type)-fe_solution(x,y,solution_2_small_ele,0,0,basis_type))*normal(2))...
       *local_basis(x,y,basis_type,0,0)'...
       *local_basis(x,y,basis_type,0,0);