function r=integrand_2_on_edges(x,y,penalty,edge_information,basis_type,eipsilon,e,beta)
%The integrand of the integral on the Dirichelet boundary edges
normal_vector=edge_information(1:2);
r=-(normal_vector(1)*local_basis(x,y,basis_type,1,0)...
   +normal_vector(2)*local_basis(x,y,basis_type,0,1))'...
  *local_basis(x,y,basis_type,0,0)...
 +eipsilon*local_basis(x,y,basis_type,0,0)'...
 *(normal_vector(1)*local_basis(x,y,basis_type,1,0)...
  +normal_vector(2)*local_basis(x,y,basis_type,0,1))...
 +1/e^beta*penalty*local_basis(x,y,basis_type,0,0)'...
                  *local_basis(x,y,basis_type,0,0);