function r=integrand_nonlinear_function_1(x,y,solution_1,solution_2,basis_type)

r=(fe_solution(x,y,solution_1,0,0,basis_type)*local_basis(x,y,basis_type,1,0)...
  +fe_solution(x,y,solution_2,0,0,basis_type)*local_basis(x,y,basis_type,0,1))'...
  *local_basis(x,y,basis_type,0,0)...
  +0.5*(fe_solution(x,y,solution_1,1,0,basis_type)+fe_solution(x,y,solution_2,0,1,basis_type))...
      *local_basis(x,y,basis_type,0,0)'...
      *local_basis(x,y,basis_type,0,0);