function r=integrand_3_on_edges(x,y,penalty,edge_information,basis_type,eipsilon,e,beta)

normal_vector=edge_information(1:2);

r=eipsilon*function_u1(x,y)...
          *(normal_vector(1)*local_basis(x,y,basis_type,1,0)...
           +normal_vector(2)*local_basis(x,y,basis_type,0,1))'...
 +1/e^beta*function_u1(x,y)...
          *penalty*local_basis(x,y,basis_type,0,0)';