function r=integrand_nonlinear_function_4(x,y,solution_1_ele,solution_2_ele,basis_type,normal)

r=-0.5*(fe_solution(x,y,solution_1_ele,0,0,basis_type)*normal(1)...
       +fe_solution(x,y,solution_2_ele,0,0,basis_type)*normal(2))...
      *local_basis(x,y,basis_type,0,0)'...
      *local_basis(x,y,basis_type,0,0);