function r=integrand_1_on_edges(x,y,penalty,edge_information_trial,edge_information_test,basis_type,eipsilon,e,beta)
%The integrand of the integral on the inner edges
normal_vector=edge_information_trial(1:2);
jump_flag_trial=edge_information_trial(3);
jump_flag_test=edge_information_test(3);
r=-0.5*(normal_vector(1)*local_basis(x,y,basis_type,1,0)...
       +normal_vector(2)*local_basis(x,y,basis_type,0,1))'...
         *jump_flag_test*local_basis(x,y,basis_type,0,0)...
  +eipsilon*0.5*jump_flag_trial*local_basis(x,y,basis_type,0,0)'...
           *(normal_vector(1)*local_basis(x,y,basis_type,1,0)...
            +normal_vector(2)*local_basis(x,y,basis_type,0,1))...
  +1/e^beta*penalty*jump_flag_trial*local_basis(x,y,basis_type,0,0)'...
                   *jump_flag_test*local_basis(x,y,basis_type,0,0);
