function r=integrand_1_on_edges(x,y,edge_information_trial,edge_information_test,basis_type,eipsilon_trial,eipsilon_test,kappa,edge,sigma_F)
%The integrand of the integral on the inner edges

normal_vector=edge_information_trial(1:2);
jump_flag_trial=edge_information_trial(3);
jump_flag_test=edge_information_test(3);
r=-0.5*eipsilon_trial*(normal_vector(1)*triangular_local_basis(x,y,basis_type,1,0)...
                      +normal_vector(2)*triangular_local_basis(x,y,basis_type,0,1))'...
                     *jump_flag_test*triangular_local_basis(x,y,basis_type,0,0)...
  +kappa*eipsilon_test*0.5*jump_flag_trial*triangular_local_basis(x,y,basis_type,0,0)'...
                          *(normal_vector(1)*triangular_local_basis(x,y,basis_type,1,0)...
                           +normal_vector(2)*triangular_local_basis(x,y,basis_type,0,1))...
  +1/edge*sigma_F*jump_flag_trial*triangular_local_basis(x,y,basis_type,0,0)'...
                 *jump_flag_test*triangular_local_basis(x,y,basis_type,0,0);